### ISSUE TITLE
KeyError:'data'的问题仍然存在

### ISSUE THREAD

**Issue by KangKaneYang** [njzjz/zhihubackup#26]
0it [00:00, ?it/s]Traceback (most recent call last):
  File "f:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\xxx\.local\bin\zhihubackup.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\pipx\venvs\zhihubackup\lib\site-packages\zhihubackup\cli.py", line 11, in main
    backup_zhihu(args.username)
  File "C:\Users\xxx\pipx\venvs\zhihubackup\lib\site-packages\zhihubackup\backup.py", line 66, in loop
    for dd in jdata["data"]:
KeyError: 'data'
0it [00:00, ?it/s]

**Comment by njzjz** [comment]
更新cookie后CI测试能过：https://github.com/njzjz/zhihubackup/actions/runs/11884285891 所以代码应该没问题。不过我考虑应该把data里面具体的报错信息打印出来

<blockquote><img src="https://opengraph.githubassets.com/b89fe52e2bd972f6632888d9cbd303ec6e293c785be3373a335fd86c361353cf/njzjz/zhihubackup" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/njzjz/zhihubackup">[pre-commit.ci] pre-commit autoupdate (#24) · njzjz/zhihubackup@25e7898</a></strong></div><div>退乎前备份知乎回答. Contribute to njzjz/zhihubackup development by creating an account on GitHub.</div></blockquote>

**Comment by KangKaneYang** [comment]
感谢回复，我再试试看
